# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: haskell-exam-project
version: '0.0.0'
github: "githubuser/haskell-exam-project"
license: MIT
author: "Author name here"
maintainer: "Author name here"
# synopsis: A new Haskeleton package.
# description: haskell-exam-project is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  source-dirs: library

executables:
  haskell-exam-project:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - haskell-exam-project
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  haskell-exam-project-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - haskell-exam-project
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  haskell-exam-project-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - haskell-exam-project
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
